CREATE TABLE "owners" (
	"id" serial PRIMARY KEY NOT NULL,
	"property_id" serial NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255),
	"phone" varchar(50),
	"mailing_address" text,
	"type" varchar(50),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "properties" (
	"id" serial PRIMARY KEY NOT NULL,
	"external_id" varchar(255),
	"apn" varchar(255) NOT NULL,
	"address" text NOT NULL,
	"owner_type" varchar(50) NOT NULL,
	"city" varchar(100),
	"state" varchar(2),
	"zip" varchar(10),
	"county" varchar(100),
	"latitude" numeric(9, 6),
	"longitude" numeric(9, 6),
	"bedrooms" integer,
	"bathrooms" numeric(3, 1),
	"square_feet" integer,
	"year_built" integer,
	"lot_acres" numeric(10, 2),
	"property_type" varchar(100),
	"building_style" varchar(100),
	"building_condition" varchar(50),
	"building_square_feet" integer,
	"ground_floor_square_feet" integer,
	"living_square_feet" integer,
	"garage_square_feet" integer,
	"garage_unfinished_square_feet" integer,
	"parking_spaces" integer,
	"construction_type" varchar(100),
	"roof_cover_type" varchar(100),
	"floor_cover_type" varchar(100),
	"exterior_wall_type" varchar(100),
	"interior_wall_type" varchar(100),
	"heating_type" varchar(100),
	"heating_fuel_type" varchar(50),
	"air_conditioning_type" varchar(100),
	"hoa" boolean DEFAULT false,
	"hoa1_name" varchar(255),
	"hoa1_type" varchar(100),
	"hoa1_amount" numeric(10, 2),
	"hoa1_frequency" varchar(50),
	"market_value" numeric(12, 2),
	"market_land_value" numeric(12, 2),
	"market_improvement_value" numeric(12, 2),
	"assessed_value" numeric(12, 2),
	"assessed_land_value" numeric(12, 2),
	"assessed_improvement_value" numeric(12, 2),
	"tax_amount" numeric(10, 2),
	"tax_year" integer,
	"assessed_year" integer,
	"vacant" boolean DEFAULT false,
	"on_market" boolean DEFAULT false,
	"owner_occupied" boolean DEFAULT true,
	"occupancy_type" varchar(50),
	"is_deleted" boolean DEFAULT false,
	"within_flood_zone" boolean DEFAULT false,
	"flood_zone_description" varchar(255),
	"estimated_value" numeric(12, 2),
	"estimated_rent_amount" numeric(10, 2),
	"estimated_equity" numeric(12, 2),
	"estimated_equity_ratio" numeric(5, 2),
	"loan_balance" numeric(12, 2),
	"loan_to_value_ratio" numeric(5, 2),
	"last_sale_date" timestamp,
	"last_sale_amount" numeric(12, 2),
	"prior_sale_date" timestamp,
	"prior_sale_amount" numeric(12, 2),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"demographics" json,
	"tax_assessments" json,
	"transactions" json,
	"listings" json,
	CONSTRAINT "properties_external_id_unique" UNIQUE("external_id")
);
--> statement-breakpoint
ALTER TABLE "owners" ADD CONSTRAINT "owners_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id") ON DELETE no action ON UPDATE no action;